---
# TODO: The actual etcd port number can be retrive from kube api.
- name: Create a new cell if not exists
  command: "vtctlclient -server {{ vtctld_endpoint }} AddCellInfo --root /{{ cell.name }} -server_address http://etcd-{{ cell.name }}-client:2379 {{ cell.name }}"
  when: 'cell.name not in cellnames.stdout'
