---
- hosts: localhost
  gather_facts: no
  roles:
    - namespace
    - rbac
    - etcd-operator

- hosts: localhost
  gather_facts: no
  roles:
    - name: etcd
      etcd_cluster_name: "{{ global_etcd_cluster_name }}"
  tasks:
    - include_role:
        name: etcd
      vars:
        etcd_cluster_name: "{{ item.name }}"
      with_items: "{{ cells }}"

- hosts: localhost
  gather_facts: no
  roles:
    - vtctld

- hosts: localhost
  gather_facts: no
  roles:
    - find-vtctld-endpoint
    - cellinfo
