---
- name: Check if the cluster already exists
  shell: "kubectl --kubeconfig={{ kubeconfig }} --namespace={{ namespace }} get EtcdCluster etcd-{{ etcd_cluster_name }}"
  register: existed
  failed_when: 'existed is failure and "NotFound" not in existed.stderr'

- name: Deploy etcd cluster
  k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: "etcd.database.coreos.com/v1beta2"
      kind: "EtcdCluster"
      metadata:
        name: "etcd-{{ etcd_cluster_name }}"
        namespace: "{{ namespace }}"
      spec:
        size: "{{ etcd_cluster_size }}"
        version: "{{ etcd_version }}"
  when: existed.rc != 0
