---
- name: Verify variables
  assert:
    that:
      - "(vttablet_num|int) > vttablet_rdonly_num|int"

- name: Create replica pods
  include_tasks: vttablet.yml
  vars:
    tablet_type: replica
    cellinfo: "{{ vttablet_cell }}"
  with_sequence: start=0 count="{{ vttablet_num|int - vttablet_rdonly_num|int }}"
  loop_control:
    loop_var: uid_index

- name: Create rdonly pods
  include_tasks: vttablet.yml
  vars:
    tablet_type: rdonly
    cellinfo: "{{ vttablet_cell }}"
  with_sequence: start="{{ vttablet_num|int - vttablet_rdonly_num|int }}" count="{{ vttablet_rdonly_num|int }}"
  loop_control:
    loop_var: uid_index

